window.PORTFOLIO_PROJECTS.push({
  id: 'kamerapreis',
  featured: true,
  titlePrefix: { text: 'Kamerapreis', style: 'italic' },
  title: '26\'',
  titleFont: 'Chiron Sung HK',
  titleItalic: false,
  titleWeight: 400,
  titleColor: '#000000',
  titleSize: '1.6rem',
  detail: 'graphic design, motion design, 2025',
  archiveBlurb: 'Honoring the people behind the camera, the German Camera Award is a prestigious, annual award for film producers, cutters & co. I had the grateful task to design the Award\'s official 2026 poster.',
  tags: ['solo', 'KISD', 'private', 'WDR'],
  previewImage: 'img/dkp/dkp-header.jpg',
  detailLayout: [
    { type: 'image', src: 'img/dkp/dkp-header.jpg', width: 'full', align: 'left', caption: null },
    { type: 'text', content: 'The German Camera Award is a prestigious annual award honoring outstanding cinematographers and editors, hosted by Westdeutscher Rundfunk (WDR). As part of a biennial project at KISD, I developed poster concepts for the award\'s public campaign. Two of about 40 posters are ultimately selected each cycle to represent the award publicly for the following two years.', width: 'full', align: 'left' },
    { type: 'spacer', size: 'md' },
    { type: 'image', src: 'img/dkp/dkp04.jpg', width: 'full', align: 'left', fit: 'contain', caption: null },
    { type: 'row', blocks: [{ type: 'text', content: 'The project gave a lot of room for visual and conceptual exploration, including feedback from a jury member ahead of the final selection. I developed three distinct concepts, each approaching the theme of cinematography from a different angle.', width: 'medium', align: 'left' }, { type: 'text', content: 'The Lens Flare was inspired by the unpredictable beauty of flares in cinematography, a visual effect that can happen by accident or be used deliberately as a stylistic device. The layered reflections in the design hint at the presence of a camera without showing one, echoing how multiple lens layers create the flare effect itself.', width: 'medium', align: 'right' }] },
    { type: 'spacer', size: 'md' },
    { type: 'imageGrid', columns: 2, images: [{ src: 'img/dkp/dkp02.jpg' }, { src: 'img/dkp/dkp03.jpg' }] },
    { type: 'text', content: 'My second concept aimed to recreate the tactile, analog feel of traditional film editing. I printed on both transparent and opaque paper and scanned the results back in, producing an effect close to the illuminated light tables once used to cut and arrange film strips by hand.', width: 'full', align: 'left' },
    { type: 'spacer', size: 'md' },
    { type: 'row', blocks: [{ type: 'image', src: 'img/dkp/dkp01.jpg', width: 'medium', align: 'left', fit: 'contain', caption: null }, { type: 'image', src: 'img/dkp/dkp05.gif', width: 'medium', align: 'left', fit: 'contain', caption: null }] },
    { type: 'row', blocks: [{ type: 'text', content: 'The third concept, ASCII Poster, questions the role of the computer in modern film production. I recorded an original video on my phone and abstracted it into ASCII code, letting the computer-generated aesthetic take over while the cinematic qualities fade into the background. This concept was selected as the winning design for the German Camera Award 2026, with the jury noting its modern, widely accessible look and its layered commentary on the role of artificial intelligence in creative work today.', width: 'medium', align: 'right' }, { type: 'text', content: '', width: 'full', align: 'left' }] },
  ],
});
