window.PORTFOLIO_PROJECTS.push({
  id: 'htsoqc',
  featured: false,
  titlePrefix: { text: 'beyond', style: 'italic' },
  title: 'Binary',
  titleFont: 'Inter',
  titleItalic: false,
  titleWeight: 500,
  titleColor: '#000000',
  titleSize: '1.5rem',
  detail: 'science communication, 2024',
  archiveBlurb: 'This project continued a tradition of collaborative travel exchanges between KISD and Parsons School of Design, New York. For our client, the German Aerospace Center (DLR), we designed an exhibition object communicating quantum computing to a broad audience.',
  tags: ['team', 'KISD', 'Parsons', 'DLR'],
  previewImage: 'img/htsoqc/htsoqc08.jpg',
  detailLayout: [
    { type: 'image', src: 'img/htsoqc/htsoqc-header.jpg', width: 'full', align: 'left', caption: null },
    { type: 'text', content: 'This project continued a tradition of collaborative travel exchanges between KISD and Parsons School of Design, New York. Our client, the German Aerospace Center (DLR), challenged us to design an exhibition object communicating quantum computing to a broad audience, tying into 2025\'s UN Year of Quantum Physics, along with a working prototype.', width: 'full', align: 'left' },
    { type: 'imageGrid', columns: 2, images: [{ src: 'img/htsoqc/htsoqc06.jpg' }, { src: 'img/htsoqc/htsoqc02.jpg' }] },
    { type: 'text', content: 'The project started with an intense entry week at Parsons in New York: rapid prototyping, concept development, presentations, and a Midjourney workshop. We stayed in close contact with DLR throughout, through regular feedback sessions with two dedicated experts, and kept iterating online after returning. We later reunited with the New York students in Amsterdam at the Waag maker center for a final sprint, presenting our concepts to Master\'s students at the Sandberg Institute and closing with a jury presentation to DLR in Cologne.', width: 'full', align: 'left' },
    { type: 'imageGrid', columns: 2, images: [{ src: 'img/htsoqc/htsoqc07.jpg' }, { src: 'img/htsoqc/htsoqc08.jpg' }] },
    { type: 'text', content: 'Our concept, Beyond Binary, answers the question of how quantum computing differs from classical computing. Two interactive flip-disc-inspired displays contrast the sequential, bit-by-bit logic of classical computers with the parallel, probabilistic behavior of quantum ones. On the quantum display, black-and-white tiles spin simultaneously to represent qubits in superposition, then suddenly stabilize into a final pattern at the moment of observation. On the classical display, tiles flip one row at a time, reflecting sequential computation. By making the unfamiliar tangible through something familiar, we gave visitors a physical, intuitive sense of quantum computation.', width: 'full', align: 'left' },
    { type: 'image', src: 'img/htsoqc/htsoqc05.jpg', width: 'full', align: 'left', fit: 'contain', caption: null },
    { type: 'image', src: 'img/htsoqc/htsoqc04.jpg', width: 'full', align: 'left', fit: 'contain', caption: null },
  ],
});
