window.PORTFOLIO_PROJECTS.push({
  id: 'mycorhizza',
  featured: true,
  titlePrefix: null,
  title: 'Mycorhizza',
  titleFont: 'Chiron Sung HK',
  titleItalic: true,
  titleWeight: 400,
  titleColor: '#000000',
  titleSize: '1.6rem',
  detail: 'installation, 2025',
  archiveBlurb: 'Mycorhizza explores the relationship between humans, technology, and nature through collaboration rather than exploitation.',
  tags: ['solo work', 'KISD'],
  previewImage: 'img/mycorhizza/mycorhizza-header.mp4',
  detailLayout: [
    { type: 'imageGrid', columns: 3, images: [{ src: 'img/mycorhizza/mycorhizza01.jpg' }, { src: 'img/mycorhizza/mycorhizza02.jpg' }, { src: 'img/mycorhizza/mycorhizza03.jpg' }] },
    { type: 'text', content: 'Mycorhizza explores the relationship between humans, technology, and nature through collaboration rather than exploitation. The installation draws on extensive research into mycorrhizal fungi and lichens. Mycorrhizal fungi are the hidden ecological backbone of every forest, field, and meadow, interconnecting plants underground into a living exchange network for nutrients and signaling chemicals — evidence of a sophisticated communication between plants and fungi. This exchange challenges typical human assumptions about competitiveness and self-interest in nature. Lichens, meanwhile, represent one of the oldest and most widespread symbioses on the planet.', width: 'full', align: 'left' },
    { type: 'image', src: 'img/mycorhizza/mycorhizza08.jpg', width: 'full', align: 'left', fit: 'cover', caption: null },
    { type: 'text', content: 'The installation picks up this collaborative spirit and asks a central question: what would a genuine collaboration between nature and technology look like? Can we move past the cultural dichotomy between the two and create something new?\nTo explore this, I built a sensor (housed in a black box) that reads volatile electrochemical signals inside a cultivated mycelium sample (in a Petri dish); signals that can be interpreted as the mycelium\'s decentralized intelligence. This signal is mapped to multiple video playback and effect parameters, altering the video\'s timeline and visual appearance in real time. The sensor, including a custom PCB, was built from scratch as a side project.', width: 'full', align: 'left' },
    { type: 'imageGrid', columns: 2, images: [{ src: 'img/mycorhizza/mycorhizza05.jpg' }, { src: 'img/mycorhizza/mycorhizza06.jpg' }] },
    { type: 'row', blocks: [{ type: 'text', content: 'In this setup, computer and mycelium enter a kind of dialectic, pushing and pulling against each other and revealing their fundamentally opposite ways of operating. The computer tries to play the video as linearly and cleanly as possible, free of distortion. The mycelium\'s behavior is dynamic, non-linear, and decentralized and its signals repeatedly', width: 'medium', align: 'left' }, { type: 'text', content: 'interrupt the computer\'s task, causing visual distortions and shifts in playback speed, up to reverse playback. Visitors can see and feel this push and pull directly on screen. Yet within this endless, never-repeating process, the two actors, whether or not they perceive themselves as collaborating, produce something genuinely new.', width: 'medium', align: 'right' }] },
    { type: 'image', src: 'img/mycorhizza/mycorhizza09.mp4', width: 'full', align: 'left', fit: 'contain', caption: null },
  ],
});
