window.PORTFOLIO_PROJECTS.push({
  id: 'regeneration-studio',
  featured: false,
  titlePrefix: null,
  title: '3D-Printing Functionally Graded Materials',
  titleFont: 'IBM Plex Mono',
  titleItalic: false,
  titleWeight: 400,
  titleColor: '#000000',
  titleSize: '1.2rem',
  detail: 'biodesign, material research, 2026',
  archiveBlurb: 'An add-on system that lets any 3D printer produce nature-inspired, functionally graded materials, cutting parts, boosting performance, and restoring recyclability.',
  tags: ['solo', 'RISD', 'Hyundai'],
  previewImage: null,
  detailLayout: [
    { type: 'image', src: null, width: 'full', align: 'left', caption: null },
    { type: 'text', content: 'Add-on system for 3D printers — developed in the Hyundai Regeneration Studio, RISD\n\nDeveloped during RISD\'s Hyundai Regeneration Studio, a collaboration exploring nature-inspired, sustainable mobility design, this project investigates functionally graded materials (FGMs): a biological principle where structures transition continuously between functional zones instead of joining separate materials together.', width: 'full', align: 'left' },
    { type: 'spacer', size: 'lg' },
    { type: 'imageGrid', columns: 2, images: [{ src: null }, { src: null }] },
    { type: 'text', content: 'Composite materials dominate automotive manufacturing for their strength-to-weight ratio, but rely on irreversibly laminating different materials, making them nearly impossible to recycle. Nature solves this differently. From tendon-to-bone junctions to chitin exoskeletons, living structures achieve high performance through continuous material gradients rather than hard joints, avoiding the "monstrous hybrids" that conventional composites become.', width: 'full', align: 'left' },
    { type: 'text', content: 'To make this technology accessible beyond research labs, I built a hybrid hardware/software add-on system that attaches to any conventional 3D printer, without modifying it, and enables true gradient printing instead of the discrete material switching most dual-cartridge printers are limited to. The system combines a custom software pipeline for translating geometry into continuous material changes, compatible biomaterials, and a custom-built extrusion controller, letting users generate and print dual-material gradient objects on their own printers.', width: 'full', align: 'left' },
    { type: 'text', content: '', width: 'full', align: 'left' },
  ],
});
