window.PORTFOLIO_PROJECTS.push({
  id: 'scans',
  featured: false,
  titlePrefix: null,
  title: 'scans',
  titleFont: 'Chiron Sung HK',
  titleItalic: false,
  titleWeight: 600,
  titleColor: '#606060',
  titleSize: '1.6rem',
  detail: 'handheld photoscans, 2026',
  archiveBlurb: 'Some scans I made during my semester abroad in Providence, RI.',
  tags: ['solo', 'personal'],
  previewImage: 'img/scans/scans-header.mp4',
  detailLayout: [
    { type: 'image', src: 'img/scans/scans-header.mp4', width: 'full', align: 'left', caption: null },
    { type: 'text', content: 'Raw and unedited scans I made during my semester abroad in Providence using a handheld document scanner.', width: 'full', align: 'left' },
    { type: 'imageGrid', columns: 3, images: [{ src: 'img/scans/scans02.jpg', fit: 'cover' }, { src: 'img/scans/scans01.jpg', fit: 'cover' }, { src: 'img/scans/scans03.jpg', fit: 'cover' }] },
    { type: 'image', src: 'img/scans/scans04.jpg', width: 'full', align: 'left', fit: 'contain', caption: null },
    { type: 'imageGrid', columns: 2, images: [{ src: 'img/scans/scans06.jpg', fit: 'cover' }, { src: 'img/scans/scans07.jpg', fit: 'cover' }] },
    { type: 'image', src: 'img/scans/scans08.jpg', width: 'full', align: 'left', fit: 'contain', caption: null },
    { type: 'imageGrid', columns: 2, images: [{ src: 'img/scans/scans09.jpg' }, { src: 'img/scans/scans10.jpg' }] },
    { type: 'image', src: 'img/scans/scans12.jpg', width: 'full', align: 'left', fit: 'contain', caption: null },
    { type: 'imageGrid', columns: 3, images: [{ src: 'img/scans/scans15.jpg' }, { src: 'img/scans/scans16.jpg' }, { src: 'img/scans/scans13.jpg' }] },
  ],
});
