window.PORTFOLIO_PROJECTS.push({
  id: 'stahlbeton',
  featured: true,
  titlePrefix: { text: 'Leo Kaminski', style: 'plain' },
  title: 'Stahlbeton',
  titleFont: 'Mea Culpa',
  titleItalic: false,
  titleWeight: 400,
  titleColor: '#15a9e9',
  titleSize: '4rem',
  detail: 'stagedesign, setdesign, 2025',
  archiveBlurb: 'For the release of my friend Leo Kaminski’s album Stahlbeton, I was given the opportunity to create a conceptual stage design for a concert in a repurposed WWII bunker in Aachen.',
  tags: ['team', 'private'],
  previewImage: 'img/stahlbeton/stahlbeton-header.mp4',
  detailLayout: [
    { type: 'image', src: 'img/stahlbeton/stahlbeton-header.mp4', width: 'full', align: 'center', caption: null },
    { type: 'text', content: 'For the release of my friend Leo Kaminski’s album Stahlbeton, I was given the opportunity to create a conceptual stage design for a concert in a repurposed WWII bunker in Aachen. The raw concrete space was an ideal setting for the album’s cold, urban aesthetic.', width: 'full', align: 'left' },
    { type: 'spacer', size: 'md' },
    { type: 'row', blocks: [{ type: 'image', src: 'img/stahlbeton/stahlbeton01.jpg', width: 'medium', align: 'right', fit: 'contain', caption: null }, { type: 'text', content: 'The stage setup abstractly referenced street lamps lining a walkway, reinforcing the album’s urban atmosphere. The colors were adapted to the visual identity of the album: cold and alien yet hopeful and pure. As another feature, we made custom point-cloud 3D-scans of urban subjects such as residential high-rises and integrated them as audio-reactive visuals in TouchDesigner to further enhance the abstract references to cold, estranged urban life.', width: 'medium', align: 'left', valign: 'bottom' }] },
    { type: 'image', src: 'img/stahlbeton/stahlbeton08.mp4', width: 'full', align: 'left', fit: 'contain', caption: null },
    { type: 'text', content: 'To develop the concept, I repeatedly listened to the album, studied its visuals, and discussed ideas with Leo. Since the event was free to attend, the budget was limited, which made reusing my own self-built, digitally controllable light fixtures especially valuable. These twelve one-meter LED bars had been constructed and refined by me independently just before this project.\n', width: 'full', align: 'left' },
    { type: 'imageGrid', columns: 2, images: [{ src: 'img/stahlbeton/stahlbeton02.jpg' }, { src: 'img/stahlbeton/stahlbeton03.jpg' }] },
    { type: 'row', blocks: [{ type: 'text', content: 'A key innovation was the modular control system I developed, which mapped musical notes in Ableton to different lighting programs and color schemes. This setup made the lights fully interactive with the music (even playable on a piano) and allowed precise synchronization, improvisation, and fine-tuning during the performance.\nA strong concept, custom technology, and immersive visuals resulted in positive feedback from the audience, Leo, and his team.', width: 'full', align: 'left' }] },
    { type: 'image', src: 'img/stahlbeton/stahlbeton07.jpg', width: 'full', align: 'left', caption: null },
  ],
});
